export { default as DashboardLayout } from "./DashboardLayout";
export { default as Events } from "./Events";
export { default as EventsCommunity } from "./EventsCommunity";
export { default as AddEvent } from "./AddEvent";
export { default as Landing } from "./Landing";
export { default as HomeLayout } from "./HomeLayout";
export { default as Register } from "./Register";
export { default as Login } from "./Login";
export { default as Error } from "./Error";
export { default as Logout } from "./Logout";
// export { default as Stats } from './Stats';
// export { default as AllJobs } from './AllJobs';
// export { default as AddJob } from './AddJob';
// export { default as EditJob } from './EditJob';
// export { default as Profile } from './Profile';
// export { default as Admin } from './Admin';
